function CamCtrl(canvas, scene) {
    var _inst = this;

    this.isManYou = false;
    this.manyouIndex = 1;
    this.awake = function (){
        this.freeCamera = new BABYLON.FreeCamera("freeCamera", new BABYLON.Vector3(0, 4,  2), scene);
        this.freeCamera.rotation.y = -1.55;
        this.freeCamera.minZ = 0.01;
        this.freeCamera.invertRotation = true;

       // this.freeCamera.setTarget(new BABYLON.Vector3(this.freeCamera.position.x-0.01, this.freeCamera.position.y, this.freeCamera.position.z));
        this.freeCamera.attachControl(canvas, true);

        if(ToolMgr.isMobel()){
            this.freeCamera.speed = 0;
            this.freeCamera.inverseRotationSpeed = 1;
        }
        else {
            this.freeCamera.speed = 0;
            this.freeCamera.inverseRotationSpeed = 0.5;

        }
    }
};
